### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tebriz159** [nawab69/steemtools#2]
Hi, I'm a utopian contributor, I just saw this project and I can make a logo for it. So, what do you say?

**Comment by nawab69** [comment]
Hi @tebriz159,

Thank you for your proposal. I need a logo for this project. If you make a good logo for steemtools, I will be happy.

**Comment by tebriz159** [comment]
Hi again @nawab69 , I've made a logo design, I've combined a tool icon with a S letter logo which is similar to steemit's logo. I've made some color variations and monochrome variations of the logo. If you like it, I'll send you all files to use it. But first, I want to ask you, which color variation do you prefer? I've used steemit's logo color for the first color variation. 2nd one is random gradient color, I think it looks good too. And for the last variation I've used steem's logo colors. Last thing I want to ask, the tool icon on the s letter I can make it transparent like the monochrome variation as you see in the picture below, which one do you prefer?

![steemtoolspr](https://user-images.githubusercontent.com/31902754/53686629-75e72680-3cde-11e9-8df4-d211a7f786ef.png)

**Comment by nawab69** [comment]
I think the 2nd logo is better for my projecf

**Comment by nawab69** [comment]
The logo look like so cool & beautiful

**Comment by tebriz159** [comment]
I like that variation too, here's all files to use it: https://drive.google.com/open?id=1o8_HIJjaEpfNKoZJPOp-nV2A9eS6I3tI

**Comment by nawab69** [comment]
Thank you. I have changed the site logo and also changed the logo in readme

**Comment by nawab69** [comment]
I have uploaded your logo to steemtools.

Thank you so much for designing the logo.
