### ISSUE TITLE
Improving the UX and UI of steemtools

### ISSUE THREAD

**Issue by zoneboy** [nawab69/steemtools#8]
# Introduction 

[Steemtools](steemtools.cf) is a website that offers many tools that are useful for many Steemit users. Some tools such as steemit post word count and checking for blacklisted account are very useful and I often use them. The website have other tools such as modifying the withdrawal route of an account and also changing a user recovery account.

# Components 
My suggestion is on the 
* Website Header 
* Check Blacklist Page 

# Proposal 

> The website looks good with the present functions and I believe it can be improved to even look better 
I propose the addition of 
* **Header logo as link option -** Visiting the site and navigating through the pages there, you will discover that there is no way to access the main menu via any link in the website. turning the header logo into a link will allow users to easily move back to the menu at any point in time with just a single click. 
* **Blacklist page navbar feature -** The navigation button in the blacklist page is not functioning. You can't visit other page on the website thereby making the page looking like a static stand-alone site. The addition of a functional navbar will solve this. 

This will be explained further in the mockups below. 

# Mockups/Examples 
https://youtu.be/_pezpKrL9eY

You can see the actual behaviour of the website in the above video.

https://youtu.be/A2jQrBTPCog

The above video showed how my proposal should work when implemented. I gave the proposed solution below.

# My Proposed Solution

In making the header logo a link, the image has to be wrapped with an anchor tag. That will give ``<a href="index.php"><img class="navbrand" src="../include/logo.png" height="50px" width="200px"></a>``

What this means is that the image  should be clickable and redirect to the homepage which is **index.php** 

In order to make sure that the blacklist navigation page is working, I observed that the bootstrap javascript links were not included on the page.

The following code should be included on the page code so that it can function well.

``` <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>```

``` <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script> ```

```<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>```

They should be pasted after the last **Div** tag just before the **body** tag 

 # Benefits 
**Header logo as a link-** Having this feature will greatly improve the website. Users will be able to move to the main menu with a single click rather than pressing the browser back button numerous times just to achieve that. It will improve the **UX** user experience **UI** user interface of the website and also reduce the time, stress involved in navigating to the home page. 

**Blacklist navbar feature-** This is another feature that will improve [Steemtools](Steemtools.cf). It will improve the website **UI** and the **UX** as users will be able to navigate to other parts of the website with ease. 

# Conclusion 

Implementation of these features will greatly improve the website. It will have a major impact on how users use the website too.

**Comment by nawab69** [comment]
Thank you @zoneboy. For your good suggestion. 

I am busy from last week .  so I can't work in online. 

Your suggestions is very helpful. I will fix this bug soon .
